# Simple workflow for deploying static content to GitHub Pages
name: Docs
on: [push]

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install pnpm package manager
        uses: pnpm/action-setup@v4
        with:
          version: 9.10.0

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install

      - name: Install TypeDoc
        run: pnpm -g install typedoc

      - name: Generate docs
        run: typedoc src/index.ts

      - name: Deploy docs
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
